# Generated by spaday.cem from custom-elements.json — do not edit by hand.
from __future__ import annotations

from typing import Any, Literal, Optional

from spaday.component import Child, Component

__all__ = ["SpButton", "SpClearButton", "SpCloseButton"]


class SpButton(Component):
    tag = "sp-button"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        pending_label: Optional[str] = None,
        pending: Optional[bool] = None,
        variant: Any = None,
        static_color: Optional[Literal["black", "white"]] = None,
        treatment: Any = None,
        quiet: Optional[bool] = None,
        no_wrap: Optional[bool] = None,
        active: Optional[bool] = None,
        type: Optional[Literal["button", "submit", "reset"]] = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "pending-label": pending_label,
                "pending": pending,
                "variant": variant,
                "static-color": static_color,
                "treatment": treatment,
                "quiet": quiet,
                "no-wrap": no_wrap,
                "active": active,
                "type": type,
            },
            **props,
        )


class SpClearButton(Component):
    tag = "sp-clear-button"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        label: Optional[str] = None,
        quiet: Optional[bool] = None,
        variant: Optional[Literal["overBackground"]] = None,
        static_color: Optional[Literal["white"]] = None,
        active: Optional[bool] = None,
        type: Optional[Literal["button", "submit", "reset"]] = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "label": label,
                "quiet": quiet,
                "variant": variant,
                "static-color": static_color,
                "active": active,
                "type": type,
            },
            **props,
        )


class SpCloseButton(Component):
    tag = "sp-close-button"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        variant: Any = None,
        static_color: Optional[Literal["black", "white"]] = None,
        active: Optional[bool] = None,
        type: Optional[Literal["button", "submit", "reset"]] = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "variant": variant,
                "static-color": static_color,
                "active": active,
                "type": type,
            },
            **props,
        )
