# Generated by spaday.cem from @spectrum-web-components/button — do not edit by hand.
from __future__ import annotations

from typing import Any, Literal

from spaday.catalog import ComponentSchema, PropertySchema
from spaday.component import Child, Component

__all__ = ["SpButton", "SpClearButton", "SpCloseButton"]


class SpButton(Component):
    tag = "sp-button"
    schema = ComponentSchema(
        tag="sp-button",
        class_name="SpButton",
        summary="",
        props=(
            PropertySchema(name="pending-label", kind="string", choices=(), default="Pending", description=None),
            PropertySchema(name="pending", kind="boolean", choices=(), default="false", description=None),
            PropertySchema(
                name="variant",
                kind="json",
                choices=(),
                type_text="ButtonVariants",
                default=None,
                description="The visual variant to apply to this button.",
            ),
            PropertySchema(
                name="static-color",
                kind="enum",
                choices=("black", "white"),
                default=None,
                description="The static color variant to use for this button.",
            ),
            PropertySchema(
                name="treatment",
                kind="json",
                choices=(),
                type_text="ButtonTreatments",
                default="fill",
                description="The visual treatment to apply to this button.",
            ),
            PropertySchema(name="quiet", kind="boolean", choices=(), default=None, description="Style this button to be less obvious."),
            PropertySchema(
                name="no-wrap",
                kind="boolean",
                choices=(),
                default=None,
                description="Disables text wrapping within the button component's label.\nPlease note that this option is not a part of the design specification\nand should be used carefully, with consideration of this overflow behavior\nand the readability of the button's content.",
            ),
            PropertySchema(name="active", kind="boolean", choices=(), default="false", description=None),
            PropertySchema(
                name="type",
                kind="enum",
                choices=("button", "submit", "reset"),
                default="button",
                description="The default behavior of the button.\nPossible values are: `button` (default), `submit`, and `reset`.",
            ),
            PropertySchema(name="disabled", kind="boolean", choices=(), default=None, description=None),
            PropertySchema(name="autofocus", kind="boolean", choices=(), default=None, description=None),
            PropertySchema(name="tabindex", kind="number", choices=(), default=None, description=None),
            PropertySchema(name="download", kind="string", choices=(), default=None, description=None),
            PropertySchema(name="label", kind="string", choices=(), default=None, description=None),
            PropertySchema(name="href", kind="string", choices=(), default=None, description=None),
            PropertySchema(name="target", kind="enum", choices=("_blank", "_parent", "_self", "_top"), default=None, description=None),
            PropertySchema(
                name="referrerpolicy",
                kind="enum",
                choices=(
                    "no-referrer",
                    "no-referrer-when-downgrade",
                    "origin",
                    "origin-when-cross-origin",
                    "same-origin",
                    "strict-origin",
                    "strict-origin-when-cross-origin",
                    "unsafe-url",
                ),
                default=None,
                description=None,
            ),
            PropertySchema(name="rel", kind="string", choices=(), default=None, description=None),
            PropertySchema(name="size", kind="enum", choices=("xxs", "xs", "s", "m", "l", "xl", "xxl"), default=None, description=None),
        ),
        fields=(
            PropertySchema(
                name="pendingStateController", kind="json", choices=(), type_text="PendingStateController<this>", default=None, description=None
            ),
        ),
        events=(),
        slots=("", "icon"),
    )

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        pending_label: str | None = None,
        pending: bool | None = None,
        variant: Any = None,
        static_color: Literal["black", "white"] | None = None,
        treatment: Any = None,
        quiet: bool | None = None,
        no_wrap: bool | None = None,
        active: bool | None = None,
        type: Literal["button", "submit", "reset"] | None = None,
        disabled: bool | None = None,
        autofocus: bool | None = None,
        tabindex: float | None = None,
        download: str | None = None,
        label: str | None = None,
        href: str | None = None,
        target: Literal["_blank", "_parent", "_self", "_top"] | None = None,
        referrerpolicy: Literal[
            "no-referrer",
            "no-referrer-when-downgrade",
            "origin",
            "origin-when-cross-origin",
            "same-origin",
            "strict-origin",
            "strict-origin-when-cross-origin",
            "unsafe-url",
        ]
        | None = None,
        rel: str | None = None,
        size: Literal["xxs", "xs", "s", "m", "l", "xl", "xxl"] | None = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "pending-label": pending_label,
                "pending": pending,
                "variant": variant,
                "static-color": static_color,
                "treatment": treatment,
                "quiet": quiet,
                "no-wrap": no_wrap,
                "active": active,
                "type": type,
                "disabled": disabled,
                "autofocus": autofocus,
                "tabindex": tabindex,
                "download": download,
                "label": label,
                "href": href,
                "target": target,
                "referrerpolicy": referrerpolicy,
                "rel": rel,
                "size": size,
            },
            **props,
        )


class SpClearButton(Component):
    tag = "sp-clear-button"
    schema = ComponentSchema(
        tag="sp-clear-button",
        class_name="SpClearButton",
        summary="",
        props=(
            PropertySchema(
                name="label",
                kind="string",
                choices=(),
                default=None,
                description="An accessible label that describes the component.\nIt will be applied to aria-label, but not visually rendered.\nThis attribute is required for clear buttons.",
            ),
            PropertySchema(name="quiet", kind="boolean", choices=(), default="false", description=None),
            PropertySchema(
                name="variant", kind="enum", choices=("overBackground",), default=None, description="The visual variant to apply to this button."
            ),
            PropertySchema(
                name="static-color", kind="enum", choices=("white",), default=None, description="The visual variant to apply to this button."
            ),
            PropertySchema(name="active", kind="boolean", choices=(), default="false", description=None),
            PropertySchema(
                name="type",
                kind="enum",
                choices=("button", "submit", "reset"),
                default="button",
                description="The default behavior of the button.\nPossible values are: `button` (default), `submit`, and `reset`.",
            ),
            PropertySchema(name="disabled", kind="boolean", choices=(), default=None, description=None),
            PropertySchema(name="autofocus", kind="boolean", choices=(), default=None, description=None),
            PropertySchema(name="tabindex", kind="number", choices=(), default=None, description=None),
            PropertySchema(name="download", kind="string", choices=(), default=None, description=None),
            PropertySchema(name="href", kind="string", choices=(), default=None, description=None),
            PropertySchema(name="target", kind="enum", choices=("_blank", "_parent", "_self", "_top"), default=None, description=None),
            PropertySchema(
                name="referrerpolicy",
                kind="enum",
                choices=(
                    "no-referrer",
                    "no-referrer-when-downgrade",
                    "origin",
                    "origin-when-cross-origin",
                    "same-origin",
                    "strict-origin",
                    "strict-origin-when-cross-origin",
                    "unsafe-url",
                ),
                default=None,
                description=None,
            ),
            PropertySchema(name="rel", kind="string", choices=(), default=None, description=None),
            PropertySchema(name="size", kind="enum", choices=("xxs", "xs", "s", "m", "l", "xl", "xxl"), default=None, description=None),
        ),
        events=(),
        slots=("", "icon"),
    )

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        label: str | None = None,
        quiet: bool | None = None,
        variant: Literal["overBackground"] | None = None,
        static_color: Literal["white"] | None = None,
        active: bool | None = None,
        type: Literal["button", "submit", "reset"] | None = None,
        disabled: bool | None = None,
        autofocus: bool | None = None,
        tabindex: float | None = None,
        download: str | None = None,
        href: str | None = None,
        target: Literal["_blank", "_parent", "_self", "_top"] | None = None,
        referrerpolicy: Literal[
            "no-referrer",
            "no-referrer-when-downgrade",
            "origin",
            "origin-when-cross-origin",
            "same-origin",
            "strict-origin",
            "strict-origin-when-cross-origin",
            "unsafe-url",
        ]
        | None = None,
        rel: str | None = None,
        size: Literal["xxs", "xs", "s", "m", "l", "xl", "xxl"] | None = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "label": label,
                "quiet": quiet,
                "variant": variant,
                "static-color": static_color,
                "active": active,
                "type": type,
                "disabled": disabled,
                "autofocus": autofocus,
                "tabindex": tabindex,
                "download": download,
                "href": href,
                "target": target,
                "referrerpolicy": referrerpolicy,
                "rel": rel,
                "size": size,
            },
            **props,
        )


class SpCloseButton(Component):
    tag = "sp-close-button"
    schema = ComponentSchema(
        tag="sp-close-button",
        class_name="SpCloseButton",
        summary="",
        props=(
            PropertySchema(
                name="variant",
                kind="json",
                choices=(),
                type_text="ButtonStaticColors | ''",
                default="",
                description="The visual variant to apply to this button.",
            ),
            PropertySchema(name="static-color", kind="enum", choices=("black", "white"), default=None, description=None),
            PropertySchema(name="active", kind="boolean", choices=(), default="false", description=None),
            PropertySchema(
                name="type",
                kind="enum",
                choices=("button", "submit", "reset"),
                default="button",
                description="The default behavior of the button.\nPossible values are: `button` (default), `submit`, and `reset`.",
            ),
            PropertySchema(name="disabled", kind="boolean", choices=(), default=None, description=None),
            PropertySchema(name="autofocus", kind="boolean", choices=(), default=None, description=None),
            PropertySchema(name="tabindex", kind="number", choices=(), default=None, description=None),
            PropertySchema(name="download", kind="string", choices=(), default=None, description=None),
            PropertySchema(name="label", kind="string", choices=(), default=None, description=None),
            PropertySchema(name="href", kind="string", choices=(), default=None, description=None),
            PropertySchema(name="target", kind="enum", choices=("_blank", "_parent", "_self", "_top"), default=None, description=None),
            PropertySchema(
                name="referrerpolicy",
                kind="enum",
                choices=(
                    "no-referrer",
                    "no-referrer-when-downgrade",
                    "origin",
                    "origin-when-cross-origin",
                    "same-origin",
                    "strict-origin",
                    "strict-origin-when-cross-origin",
                    "unsafe-url",
                ),
                default=None,
                description=None,
            ),
            PropertySchema(name="rel", kind="string", choices=(), default=None, description=None),
            PropertySchema(name="size", kind="enum", choices=("xxs", "xs", "s", "m", "l", "xl", "xxl"), default=None, description=None),
        ),
        events=(),
        slots=("", "icon"),
    )

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        variant: Any = None,
        static_color: Literal["black", "white"] | None = None,
        active: bool | None = None,
        type: Literal["button", "submit", "reset"] | None = None,
        disabled: bool | None = None,
        autofocus: bool | None = None,
        tabindex: float | None = None,
        download: str | None = None,
        label: str | None = None,
        href: str | None = None,
        target: Literal["_blank", "_parent", "_self", "_top"] | None = None,
        referrerpolicy: Literal[
            "no-referrer",
            "no-referrer-when-downgrade",
            "origin",
            "origin-when-cross-origin",
            "same-origin",
            "strict-origin",
            "strict-origin-when-cross-origin",
            "unsafe-url",
        ]
        | None = None,
        rel: str | None = None,
        size: Literal["xxs", "xs", "s", "m", "l", "xl", "xxl"] | None = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "variant": variant,
                "static-color": static_color,
                "active": active,
                "type": type,
                "disabled": disabled,
                "autofocus": autofocus,
                "tabindex": tabindex,
                "download": download,
                "label": label,
                "href": href,
                "target": target,
                "referrerpolicy": referrerpolicy,
                "rel": rel,
                "size": size,
            },
            **props,
        )
