# Generated by spaday.cem from custom-elements.json — do not edit by hand.
from __future__ import annotations

from typing import Any, Literal

from spaday.component import Child, Component

__all__ = ["SpButton", "SpClearButton", "SpCloseButton"]


class SpButton(Component):
    tag = "sp-button"

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        pending_label: str | None = None,
        pending: bool | None = None,
        variant: Any = None,
        static_color: Literal["black", "white"] | None = None,
        treatment: Any = None,
        quiet: bool | None = None,
        no_wrap: bool | None = None,
        active: bool | None = None,
        type: Literal["button", "submit", "reset"] | None = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "pending-label": pending_label,
                "pending": pending,
                "variant": variant,
                "static-color": static_color,
                "treatment": treatment,
                "quiet": quiet,
                "no-wrap": no_wrap,
                "active": active,
                "type": type,
            },
            **props,
        )


class SpClearButton(Component):
    tag = "sp-clear-button"

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        label: str | None = None,
        quiet: bool | None = None,
        variant: Literal["overBackground"] | None = None,
        static_color: Literal["white"] | None = None,
        active: bool | None = None,
        type: Literal["button", "submit", "reset"] | None = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "label": label,
                "quiet": quiet,
                "variant": variant,
                "static-color": static_color,
                "active": active,
                "type": type,
            },
            **props,
        )


class SpCloseButton(Component):
    tag = "sp-close-button"

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        variant: Any = None,
        static_color: Literal["black", "white"] | None = None,
        active: bool | None = None,
        type: Literal["button", "submit", "reset"] | None = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "variant": variant,
                "static-color": static_color,
                "active": active,
                "type": type,
            },
            **props,
        )
