# Generated by spaday.cem from custom-elements.json — do not edit by hand.
from __future__ import annotations

from typing import Any

from spaday.component import Child, Component

__all__ = ["SpCheckbox"]


class SpCheckbox(Component):
    tag = "sp-checkbox"

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        disabled: bool | None = None,
        indeterminate: bool | None = None,
        invalid: bool | None = None,
        emphasized: bool | None = None,
        tabindex: float | None = None,
        checked: bool | None = None,
        name: str | None = None,
        readonly: bool | None = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "disabled": disabled,
                "indeterminate": indeterminate,
                "invalid": invalid,
                "emphasized": emphasized,
                "tabindex": tabindex,
                "checked": checked,
                "name": name,
                "readonly": readonly,
            },
            **props,
        )
