# Generated by spaday.cem from @spectrum-web-components/checkbox — do not edit by hand.
from __future__ import annotations

from typing import Any, Literal

from spaday.catalog import ComponentSchema, PropertySchema
from spaday.component import Child, Component

__all__ = ["SpCheckbox"]


class SpCheckbox(Component):
    tag = "sp-checkbox"
    schema = ComponentSchema(
        tag="sp-checkbox",
        class_name="SpCheckbox",
        summary="",
        props=(
            PropertySchema(
                name="disabled", kind="boolean", choices=(), default="false", description="Disable this control. It will not receive focus or events"
            ),
            PropertySchema(name="indeterminate", kind="boolean", choices=(), default="false", description=None),
            PropertySchema(name="invalid", kind="boolean", choices=(), default="false", description=None),
            PropertySchema(name="emphasized", kind="boolean", choices=(), default="false", description=None),
            PropertySchema(name="tabindex", kind="number", choices=(), default="0", description=None),
            PropertySchema(name="checked", kind="boolean", choices=(), default="false", description=None),
            PropertySchema(name="name", kind="string", choices=(), default=None, description=None),
            PropertySchema(name="readonly", kind="boolean", choices=(), default="false", description=None),
            PropertySchema(name="size", kind="enum", choices=("xxs", "xs", "s", "m", "l", "xl", "xxl"), default=None, description=None),
        ),
        events=("change",),
        slots=("",),
    )

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        disabled: bool | None = None,
        indeterminate: bool | None = None,
        invalid: bool | None = None,
        emphasized: bool | None = None,
        tabindex: float | None = None,
        checked: bool | None = None,
        name: str | None = None,
        readonly: bool | None = None,
        size: Literal["xxs", "xs", "s", "m", "l", "xl", "xxl"] | None = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "disabled": disabled,
                "indeterminate": indeterminate,
                "invalid": invalid,
                "emphasized": emphasized,
                "tabindex": tabindex,
                "checked": checked,
                "name": name,
                "readonly": readonly,
                "size": size,
            },
            **props,
        )
