# Generated by spaday.cem from custom-elements.json — do not edit by hand.
from __future__ import annotations

from typing import Any, Optional

from spaday.component import Child, Component

__all__ = ["SpCheckbox"]


class SpCheckbox(Component):
    tag = "sp-checkbox"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        disabled: Optional[bool] = None,
        indeterminate: Optional[bool] = None,
        invalid: Optional[bool] = None,
        emphasized: Optional[bool] = None,
        tabindex: Optional[float] = None,
        checked: Optional[bool] = None,
        name: Optional[str] = None,
        readonly: Optional[bool] = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "disabled": disabled,
                "indeterminate": indeterminate,
                "invalid": invalid,
                "emphasized": emphasized,
                "tabindex": tabindex,
                "checked": checked,
                "name": name,
                "readonly": readonly,
            },
            **props,
        )
