# Generated by spaday.cem from custom-elements.json — do not edit by hand.
from __future__ import annotations

from typing import Any

from spaday.component import Child, Component

__all__ = ["SpSwitch"]


class SpSwitch(Component):
    tag = "sp-switch"

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        emphasized: bool | None = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "emphasized": emphasized,
            },
            **props,
        )
