# Generated by spaday.cem from @spectrum-web-components/switch — do not edit by hand.
from __future__ import annotations

from typing import Any, Literal

from spaday.catalog import ComponentSchema, PropertySchema
from spaday.component import Child, Component

__all__ = ["SpSwitch"]


class SpSwitch(Component):
    tag = "sp-switch"
    schema = ComponentSchema(
        tag="sp-switch",
        class_name="SpSwitch",
        summary="",
        props=(
            PropertySchema(name="emphasized", kind="boolean", choices=(), default="false", description=None),
            PropertySchema(name="checked", kind="boolean", choices=(), default="false", description=None),
            PropertySchema(name="name", kind="string", choices=(), default=None, description=None),
            PropertySchema(name="readonly", kind="boolean", choices=(), default="false", description=None),
            PropertySchema(name="disabled", kind="boolean", choices=(), default=None, description=None),
            PropertySchema(name="autofocus", kind="boolean", choices=(), default=None, description=None),
            PropertySchema(name="tabindex", kind="number", choices=(), default=None, description=None),
            PropertySchema(name="size", kind="enum", choices=("xxs", "xs", "s", "m", "l", "xl", "xxl"), default=None, description=None),
        ),
        events=("change",),
        slots=("",),
    )

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        emphasized: bool | None = None,
        checked: bool | None = None,
        name: str | None = None,
        readonly: bool | None = None,
        disabled: bool | None = None,
        autofocus: bool | None = None,
        tabindex: float | None = None,
        size: Literal["xxs", "xs", "s", "m", "l", "xl", "xxl"] | None = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "emphasized": emphasized,
                "checked": checked,
                "name": name,
                "readonly": readonly,
                "disabled": disabled,
                "autofocus": autofocus,
                "tabindex": tabindex,
                "size": size,
            },
            **props,
        )
