# Generated by spaday.cem from custom-elements.json — do not edit by hand.
from __future__ import annotations

from typing import Any, Literal, Optional

from spaday.component import Child, Component

__all__ = ["SpTab", "SpTabPanel", "SpTabs", "SpTabsOverflow"]


class SpTab(Component):
    tag = "sp-tab"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        disabled: Optional[bool] = None,
        label: Optional[str] = None,
        selected: Optional[bool] = None,
        vertical: Optional[bool] = None,
        value: Optional[str] = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "disabled": disabled,
                "label": label,
                "selected": selected,
                "vertical": vertical,
                "value": value,
            },
            **props,
        )


class SpTabPanel(Component):
    tag = "sp-tab-panel"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        selected: Optional[bool] = None,
        value: Optional[str] = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "selected": selected,
                "value": value,
            },
            **props,
        )


class SpTabs(Component):
    tag = "sp-tabs"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        auto: Optional[bool] = None,
        compact: Optional[bool] = None,
        dir: Optional[Literal["ltr", "rtl"]] = None,
        direction: Optional[Literal["vertical", "vertical-right", "horizontal"]] = None,
        emphasized: Optional[bool] = None,
        label: Optional[str] = None,
        enableTabsScroll: Optional[bool] = None,
        quiet: Optional[bool] = None,
        selected: Optional[str] = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "auto": auto,
                "compact": compact,
                "dir": dir,
                "direction": direction,
                "emphasized": emphasized,
                "label": label,
                "enableTabsScroll": enableTabsScroll,
                "quiet": quiet,
                "selected": selected,
            },
            **props,
        )


class SpTabsOverflow(Component):
    tag = "sp-tabs-overflow"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        compact: Optional[bool] = None,
        label_previous: Optional[str] = None,
        label_next: Optional[str] = None,
        dir: Optional[Literal["ltr", "rtl"]] = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "compact": compact,
                "label-previous": label_previous,
                "label-next": label_next,
                "dir": dir,
            },
            **props,
        )
