# Generated by spaday.cem from @spectrum-web-components/tabs — do not edit by hand.
from __future__ import annotations

from typing import Any, Literal

from spaday.catalog import ComponentSchema, PropertySchema
from spaday.component import Child, Component

__all__ = ["SpTab", "SpTabPanel", "SpTabs", "SpTabsOverflow"]


class SpTab(Component):
    tag = "sp-tab"
    schema = ComponentSchema(
        tag="sp-tab",
        class_name="SpTab",
        summary="",
        props=(
            PropertySchema(name="disabled", kind="boolean", choices=(), default="false", description=None),
            PropertySchema(name="label", kind="string", choices=(), default="", description=None),
            PropertySchema(name="selected", kind="boolean", choices=(), default="false", description=None),
            PropertySchema(name="vertical", kind="boolean", choices=(), default="false", description=None),
            PropertySchema(name="value", kind="string", choices=(), default="", description=None),
        ),
        events=(),
        slots=("", "icon"),
    )

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        disabled: bool | None = None,
        label: str | None = None,
        selected: bool | None = None,
        vertical: bool | None = None,
        value: str | None = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "disabled": disabled,
                "label": label,
                "selected": selected,
                "vertical": vertical,
                "value": value,
            },
            **props,
        )


class SpTabPanel(Component):
    tag = "sp-tab-panel"
    schema = ComponentSchema(
        tag="sp-tab-panel",
        class_name="SpTabPanel",
        summary="",
        props=(
            PropertySchema(name="selected", kind="boolean", choices=(), default="false", description=None),
            PropertySchema(name="value", kind="string", choices=(), default="", description=None),
        ),
        events=(),
        slots=("",),
    )

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        selected: bool | None = None,
        value: str | None = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "selected": selected,
                "value": value,
            },
            **props,
        )


class SpTabs(Component):
    tag = "sp-tabs"
    schema = ComponentSchema(
        tag="sp-tabs",
        class_name="SpTabs",
        summary="",
        props=(
            PropertySchema(
                name="auto",
                kind="boolean",
                choices=(),
                default="false",
                description='Whether to activate a tab on keyboard focus or not.\n\nBy default a tab is activated via a "click" interaction. This is specifically intended for when\ntab content cannot be displayed instantly, e.g. not all of the DOM content is available, etc.\nTo learn more about "Deciding When to Make Selection Automatically Follow Focus", visit:\nhttps://w3c.github.io/aria-practices/#kbd_selection_follows_focus',
            ),
            PropertySchema(name="compact", kind="boolean", choices=(), default="false", description="The tab items are displayed closer together."),
            PropertySchema(
                name="direction", kind="enum", choices=("vertical", "vertical-right", "horizontal"), default="horizontal", description=None
            ),
            PropertySchema(name="emphasized", kind="boolean", choices=(), default="false", description=None),
            PropertySchema(name="label", kind="string", choices=(), default="", description=None),
            PropertySchema(name="enableTabsScroll", kind="boolean", choices=(), default="false", description=None),
            PropertySchema(name="quiet", kind="boolean", choices=(), default="false", description="The tab list is displayed without a border."),
            PropertySchema(name="selected", kind="string", choices=(), default="", description=None),
            PropertySchema(name="disabled", kind="boolean", choices=(), default=None, description=None),
            PropertySchema(name="autofocus", kind="boolean", choices=(), default=None, description=None),
            PropertySchema(name="tabindex", kind="number", choices=(), default=None, description=None),
            PropertySchema(name="size", kind="enum", choices=("xxs", "xs", "s", "m", "l", "xl", "xxl"), default=None, description=None),
        ),
        fields=(
            PropertySchema(name="selectionIndicatorStyle", kind="json", choices=(), default=None, description=None),
            PropertySchema(name="shouldAnimate", kind="boolean", choices=(), default="false", description=None),
            PropertySchema(name="rovingTabindexController", kind="json", choices=(), default=None, description=None),
        ),
        events=("change",),
        slots=("", "tab-panel"),
    )

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        auto: bool | None = None,
        compact: bool | None = None,
        direction: Literal["vertical", "vertical-right", "horizontal"] | None = None,
        emphasized: bool | None = None,
        label: str | None = None,
        enableTabsScroll: bool | None = None,
        quiet: bool | None = None,
        selected: str | None = None,
        disabled: bool | None = None,
        autofocus: bool | None = None,
        tabindex: float | None = None,
        size: Literal["xxs", "xs", "s", "m", "l", "xl", "xxl"] | None = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "auto": auto,
                "compact": compact,
                "direction": direction,
                "emphasized": emphasized,
                "label": label,
                "enableTabsScroll": enableTabsScroll,
                "quiet": quiet,
                "selected": selected,
                "disabled": disabled,
                "autofocus": autofocus,
                "tabindex": tabindex,
                "size": size,
            },
            **props,
        )


class SpTabsOverflow(Component):
    tag = "sp-tabs-overflow"
    schema = ComponentSchema(
        tag="sp-tabs-overflow",
        class_name="SpTabsOverflow",
        summary="",
        props=(
            PropertySchema(name="compact", kind="boolean", choices=(), default="false", description=None),
            PropertySchema(name="label-previous", kind="string", choices=(), default="Scroll to previous tabs", description=None),
            PropertySchema(name="label-next", kind="string", choices=(), default="Scroll to next tabs", description=None),
            PropertySchema(name="size", kind="enum", choices=("xxs", "xs", "s", "m", "l", "xl", "xxl"), default=None, description=None),
        ),
        fields=(PropertySchema(name="resizeController", kind="json", choices=(), type_text="ResizeController", default=None, description=None),),
        events=(),
        slots=(),
    )

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        compact: bool | None = None,
        label_previous: str | None = None,
        label_next: str | None = None,
        size: Literal["xxs", "xs", "s", "m", "l", "xl", "xxl"] | None = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "compact": compact,
                "label-previous": label_previous,
                "label-next": label_next,
                "size": size,
            },
            **props,
        )
