# Generated by spaday.cem from custom-elements.json — do not edit by hand.
from __future__ import annotations

from typing import Any, Literal

from spaday.component import Child, Component

__all__ = ["SpTab", "SpTabPanel", "SpTabs", "SpTabsOverflow"]


class SpTab(Component):
    tag = "sp-tab"

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        disabled: bool | None = None,
        label: str | None = None,
        selected: bool | None = None,
        vertical: bool | None = None,
        value: str | None = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "disabled": disabled,
                "label": label,
                "selected": selected,
                "vertical": vertical,
                "value": value,
            },
            **props,
        )


class SpTabPanel(Component):
    tag = "sp-tab-panel"

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        selected: bool | None = None,
        value: str | None = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "selected": selected,
                "value": value,
            },
            **props,
        )


class SpTabs(Component):
    tag = "sp-tabs"

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        auto: bool | None = None,
        compact: bool | None = None,
        dir: Literal["ltr", "rtl"] | None = None,
        direction: Literal["vertical", "vertical-right", "horizontal"] | None = None,
        emphasized: bool | None = None,
        label: str | None = None,
        enableTabsScroll: bool | None = None,
        quiet: bool | None = None,
        selected: str | None = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "auto": auto,
                "compact": compact,
                "dir": dir,
                "direction": direction,
                "emphasized": emphasized,
                "label": label,
                "enableTabsScroll": enableTabsScroll,
                "quiet": quiet,
                "selected": selected,
            },
            **props,
        )


class SpTabsOverflow(Component):
    tag = "sp-tabs-overflow"

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        compact: bool | None = None,
        label_previous: str | None = None,
        label_next: str | None = None,
        dir: Literal["ltr", "rtl"] | None = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "compact": compact,
                "label-previous": label_previous,
                "label-next": label_next,
                "dir": dir,
            },
            **props,
        )
