# Generated by spaday.cem from @spectrum-web-components/textfield — do not edit by hand.
from __future__ import annotations

from typing import Any, Literal

from spaday.catalog import ComponentSchema, PropertySchema
from spaday.component import Child, Component

__all__ = ["SpTextfield"]


class SpTextfield(Component):
    tag = "sp-textfield"
    schema = ComponentSchema(
        tag="sp-textfield",
        class_name="SpTextfield",
        summary="",
        props=(
            PropertySchema(
                name="value", kind="json", choices=(), type_text="string | number", default=None, description="The value held by the form control"
            ),
            PropertySchema(
                name="allowed-keys",
                kind="string",
                choices=(),
                default="",
                description="A regular expression outlining the keys that will be allowed to update the value of the form control.",
            ),
            PropertySchema(name="focused", kind="boolean", choices=(), default="false", description=None),
            PropertySchema(
                name="invalid", kind="boolean", choices=(), default="false", description="Whether the `value` held by the form control is invalid."
            ),
            PropertySchema(
                name="label",
                kind="string",
                choices=(),
                default="",
                description="A string applied via `aria-label` to the form control when a user visible label is not provided.",
            ),
            PropertySchema(name="name", kind="string", choices=(), default=None, description="Name of the form control."),
            PropertySchema(
                name="placeholder",
                kind="string",
                choices=(),
                default="",
                description="Text that appears in the form control when it has no value set",
            ),
            PropertySchema(name="type", kind="json", choices=(), type_text="TextfieldType", default="text", description=None),
            PropertySchema(name="pattern", kind="string", choices=(), default=None, description="Pattern the `value` must match to be valid"),
            PropertySchema(
                name="grows",
                kind="boolean",
                choices=(),
                default="false",
                description="Whether a form control delivered with the `multiline` attribute will change size\nvertically to accomodate longer input",
            ),
            PropertySchema(
                name="maxlength", kind="number", choices=(), default="-1", description="Defines the maximum string length that the user can enter"
            ),
            PropertySchema(
                name="minlength", kind="number", choices=(), default="-1", description="Defines the minimum string length that the user can enter"
            ),
            PropertySchema(
                name="multiline",
                kind="boolean",
                choices=(),
                default="false",
                description="Whether the form control should accept a value longer than one line",
            ),
            PropertySchema(
                name="readonly",
                kind="boolean",
                choices=(),
                default="false",
                description="Whether a user can interact with the value of the form control",
            ),
            PropertySchema(
                name="tooltip-placement",
                kind="json",
                choices=(),
                type_text="Placement",
                default="bottom",
                description="Placement of the tooltip shown when the value is truncated (e.g. 'bottom', 'top').\nDefaults to 'bottom' per Spectrum design.",
            ),
            PropertySchema(
                name="rows",
                kind="number",
                choices=(),
                default="-1",
                description="The specific number of rows the form control should provide in the user interface",
            ),
            PropertySchema(
                name="valid", kind="boolean", choices=(), default="false", description="Whether the `value` held by the form control is valid."
            ),
            PropertySchema(
                name="quiet",
                kind="boolean",
                choices=(),
                default="false",
                description="Whether to display the form control with no visible background",
            ),
            PropertySchema(
                name="required",
                kind="boolean",
                choices=(),
                default="false",
                description="Whether the form control will be found to be invalid when it holds no `value`",
            ),
            PropertySchema(
                name="autocomplete",
                kind="json",
                choices=(),
                type_text="| 'list' | 'none' | HTMLInputElement['autocomplete'] | HTMLTextAreaElement['autocomplete'] | undefined",
                default=None,
                description="What form of assistance should be provided when attempting to supply a value to the form control\n\nNote: combobox overrides `autocomplete` intentionally with `aria-autocomplete` values, which is\nwhy those values (although invalid for native `autocomplete`) are included here to support the\ncombobox accessibility pattern.",
            ),
            PropertySchema(name="disabled", kind="boolean", choices=(), default=None, description=None),
            PropertySchema(name="autofocus", kind="boolean", choices=(), default=None, description=None),
            PropertySchema(name="tabindex", kind="number", choices=(), default=None, description=None),
            PropertySchema(name="size", kind="enum", choices=("xxs", "xs", "s", "m", "l", "xl", "xxl"), default=None, description=None),
        ),
        events=("change", "input"),
        slots=("help-text", "negative-help-text"),
    )

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        value: Any = None,
        allowed_keys: str | None = None,
        focused: bool | None = None,
        invalid: bool | None = None,
        label: str | None = None,
        name: str | None = None,
        placeholder: str | None = None,
        type: Any = None,
        pattern: str | None = None,
        grows: bool | None = None,
        maxlength: float | None = None,
        minlength: float | None = None,
        multiline: bool | None = None,
        readonly: bool | None = None,
        tooltip_placement: Any = None,
        rows: float | None = None,
        valid: bool | None = None,
        quiet: bool | None = None,
        required: bool | None = None,
        autocomplete: Any = None,
        disabled: bool | None = None,
        autofocus: bool | None = None,
        tabindex: float | None = None,
        size: Literal["xxs", "xs", "s", "m", "l", "xl", "xxl"] | None = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "value": value,
                "allowed-keys": allowed_keys,
                "focused": focused,
                "invalid": invalid,
                "label": label,
                "name": name,
                "placeholder": placeholder,
                "type": type,
                "pattern": pattern,
                "grows": grows,
                "maxlength": maxlength,
                "minlength": minlength,
                "multiline": multiline,
                "readonly": readonly,
                "tooltip-placement": tooltip_placement,
                "rows": rows,
                "valid": valid,
                "quiet": quiet,
                "required": required,
                "autocomplete": autocomplete,
                "disabled": disabled,
                "autofocus": autofocus,
                "tabindex": tabindex,
                "size": size,
            },
            **props,
        )
