# Generated by spaday.cem from custom-elements.json — do not edit by hand.
from __future__ import annotations

from typing import Any, Optional

from spaday.component import Child, Component

__all__ = ["SpTextfield"]


class SpTextfield(Component):
    tag = "sp-textfield"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        value: Any = None,
        allowed_keys: Optional[str] = None,
        focused: Optional[bool] = None,
        invalid: Optional[bool] = None,
        label: Optional[str] = None,
        name: Optional[str] = None,
        placeholder: Optional[str] = None,
        type: Any = None,
        pattern: Optional[str] = None,
        grows: Optional[bool] = None,
        maxlength: Optional[float] = None,
        minlength: Optional[float] = None,
        multiline: Optional[bool] = None,
        readonly: Optional[bool] = None,
        rows: Optional[float] = None,
        valid: Optional[bool] = None,
        quiet: Optional[bool] = None,
        required: Optional[bool] = None,
        autocomplete: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "value": value,
                "allowed-keys": allowed_keys,
                "focused": focused,
                "invalid": invalid,
                "label": label,
                "name": name,
                "placeholder": placeholder,
                "type": type,
                "pattern": pattern,
                "grows": grows,
                "maxlength": maxlength,
                "minlength": minlength,
                "multiline": multiline,
                "readonly": readonly,
                "rows": rows,
                "valid": valid,
                "quiet": quiet,
                "required": required,
                "autocomplete": autocomplete,
            },
            **props,
        )
