# Generated by spaday.cem from custom-elements.json — do not edit by hand.
from __future__ import annotations

from typing import Any

from spaday.component import Child, Component

__all__ = ["SpTextfield"]


class SpTextfield(Component):
    tag = "sp-textfield"

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        value: Any = None,
        allowed_keys: str | None = None,
        focused: bool | None = None,
        invalid: bool | None = None,
        label: str | None = None,
        name: str | None = None,
        placeholder: str | None = None,
        type: Any = None,
        pattern: str | None = None,
        grows: bool | None = None,
        maxlength: float | None = None,
        minlength: float | None = None,
        multiline: bool | None = None,
        readonly: bool | None = None,
        rows: float | None = None,
        valid: bool | None = None,
        quiet: bool | None = None,
        required: bool | None = None,
        autocomplete: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "value": value,
                "allowed-keys": allowed_keys,
                "focused": focused,
                "invalid": invalid,
                "label": label,
                "name": name,
                "placeholder": placeholder,
                "type": type,
                "pattern": pattern,
                "grows": grows,
                "maxlength": maxlength,
                "minlength": minlength,
                "multiline": multiline,
                "readonly": readonly,
                "rows": rows,
                "valid": valid,
                "quiet": quiet,
                "required": required,
                "autocomplete": autocomplete,
            },
            **props,
        )
