# Generated by spaday.cem from custom-elements.json — do not edit by hand.
from __future__ import annotations

from typing import Any, Literal

from spaday.component import Child, Component

__all__ = ["SpTheme"]


class SpTheme(Component):
    tag = "sp-theme"

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        color: Literal["lightest", "light", "dark", "darkest", ""] | None = None,
        scale: Literal["medium", "large", ""] | None = None,
        lang: str | None = None,
        dir: Literal["ltr", "rtl", ""] | None = None,
        system: Literal["spectrum", "express"] | None = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "color": color,
                "scale": scale,
                "lang": lang,
                "dir": dir,
                "system": system,
            },
            **props,
        )
