# Generated by spaday.cem from @spectrum-web-components/theme — do not edit by hand.
from __future__ import annotations

from typing import Any, Literal

from spaday.catalog import ComponentSchema, PropertySchema
from spaday.component import Child, Component

__all__ = ["SpTheme"]


class SpTheme(Component):
    tag = "sp-theme"
    schema = ComponentSchema(
        tag="sp-theme",
        class_name="SpTheme",
        summary="",
        props=(
            PropertySchema(
                name="color",
                kind="enum",
                choices=("lightest", "light", "dark", "darkest", ""),
                default=None,
                description="The Spectrum color stops to apply to content scoped by this `sp-theme` element.\n\nA value is required.",
            ),
            PropertySchema(
                name="scale",
                kind="enum",
                choices=("medium", "large", ""),
                default=None,
                description="The Spectrum platform scale to apply to content scoped by this `sp-theme` element.\n\nA value is required.",
            ),
            PropertySchema(
                name="lang",
                kind="string",
                choices=(),
                default="",
                description='The language of the content scoped to this `sp-theme` element, see: <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang" target="_blank">MDN reference</a>.',
            ),
            PropertySchema(
                name="system",
                kind="enum",
                choices=("spectrum", "express"),
                default=None,
                description="The Spectrum system that is applied to the content scoped to this `sp-theme` element.\n\nA value is required.",
            ),
        ),
        fields=(PropertySchema(name="updateComplete", kind="json", choices=(), type_text="Promise<boolean>", default=None, description=None),),
        events=(),
        slots=("",),
    )

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        color: Literal["lightest", "light", "dark", "darkest", ""] | None = None,
        scale: Literal["medium", "large", ""] | None = None,
        lang: str | None = None,
        system: Literal["spectrum", "express"] | None = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "color": color,
                "scale": scale,
                "lang": lang,
                "system": system,
            },
            **props,
        )
