# Generated by spaday.cem from custom-elements.json — do not edit by hand.
from __future__ import annotations

from typing import Any, Literal, Optional

from spaday.component import Child, Component

__all__ = ["SpTheme"]


class SpTheme(Component):
    tag = "sp-theme"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        color: Optional[Literal["lightest", "light", "dark", "darkest", ""]] = None,
        scale: Optional[Literal["medium", "large", ""]] = None,
        lang: Optional[str] = None,
        dir: Optional[Literal["ltr", "rtl", ""]] = None,
        system: Optional[Literal["spectrum", "express"]] = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "color": color,
                "scale": scale,
                "lang": lang,
                "dir": dir,
                "system": system,
            },
            **props,
        )
